# Generated by Django 2.0 on 2017-12-29 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao_n', models.IntegerField(default=0, verbose_name='Nº Solicitação')),
                ('responsavel', models.CharField(max_length=30, verbose_name='Responsável')),
                ('complexidade', models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], max_length=10)),
                ('recursos', models.CharField(choices=[('Próprio', 'Próprio'), ('Outros', 'Outros')], max_length=100)),
                ('outro_recurso', models.CharField(blank=True, max_length=60, verbose_name='Outro Recurso')),
                ('estimativa', models.IntegerField(default=1, verbose_name='Estimativa para a ação?')),
                ('viabilidade', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5)),
                ('data_prev', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data Prevista')),
            ],
        ),
        migrations.CreateModel(
            name='ModelGerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
                ('gerencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.ModelGerencia')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSolicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidade')),
                ('gerencia', models.CharField(max_length=60, verbose_name='Gerência')),
                ('setor', models.CharField(max_length=60, verbose_name='Setor')),
                ('solicitante', models.CharField(max_length=60, verbose_name='Solicitante')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('tipo_evento', models.CharField(choices=[('Curso', 'Curso'), ('Capacitação', 'Capacitação'), ('Treinamento', 'Treinamento'), ('Educação Continuada', 'Educação Continuada'), ('Congresso', 'Congresso'), ('Outros', 'Outros')], max_length=20)),
                ('outro_evento', models.CharField(blank=True, max_length=60, verbose_name='Outro Evento')),
                ('justificativa', models.TextField(max_length=500, verbose_name='Justificativa')),
                ('diagnostico', models.TextField(max_length=500, verbose_name='Diagnóstico Situacional')),
                ('prioridade', models.CharField(choices=[('Alta', 'Alta'), ('Moderada', 'Moderada'), ('Baixa', 'Baixa')], max_length=10)),
                ('evento_realizado', models.CharField(choices=[('Setor', 'Setor'), ('Individual', 'Individual'), ('Categoria', 'Categoria'), ('Qual', 'Qual')], max_length=10)),
                ('qual_evento', models.CharField(blank=True, max_length=60, verbose_name='Qual Evento')),
                ('qtd_participante', models.IntegerField(default=1, verbose_name='Quantidade de Participantes')),
                ('part_individual', models.TextField(blank=True, max_length=500, verbose_name='Participação Individual')),
                ('eixo_basico', models.CharField(choices=[('Educação Permanente em Saúde', 'Educação Permanente em Saúde'), ('Comunicação Corporativa', 'Comunicação Corporativa'), ('Relacionamento Interpessoal', 'Relacionamento Interpessoal'), ('Treinamento em Informática e Sistemas de Informação', 'Treinamento em Informática e Sistemas de Informação'), ('Humanização', 'Humanização')], max_length=55)),
                ('acao_nao_vinculada', models.TextField(blank=True, max_length=500, verbose_name='Ação Não Vinculada')),
                ('impacto_esperado_instituicao', models.TextField(max_length=500, verbose_name='Impacto Institucional')),
                ('impacto_esperado_setor', models.TextField(max_length=500, verbose_name='Impacto no Setor')),
                ('mensuracao', models.TextField(max_length=500, verbose_name='Mensuração dos Dados')),
            ],
        ),
        migrations.CreateModel(
            name='ModelUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_login', models.CharField(max_length=30, verbose_name='Usuário')),
                ('primeiro_nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('ultimo_nome', models.CharField(max_length=30, verbose_name='Último Nome')),
                ('setor', models.CharField(default='', max_length=100, verbose_name='Setor')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='modelperfil',
            name='setor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.ModelSetor'),
        ),
        migrations.AddField(
            model_name='modelperfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
