# Generated by Django 2.0 on 2017-12-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelusuario',
            name='setor',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Setor'),
        ),
    ]
