# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20171229_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelusuario',
            name='setor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Setor'),
        ),
    ]
