# Generated by Django 2.0 on 2017-12-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_auto_20171229_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsolicitacao',
            name='eixo_basico',
            field=models.CharField(choices=[('Educação Permanente em Saúde', 'Educação Permanente em Saúde'), ('Comunicação Corporativa', 'Comunicação Corporativa'), ('Relacionamento Interpessoal', 'Relacionamento Interpessoal'), ('Desenvolvimento e Acompanhamento de Projetos', 'Desenvolvimento e Acompanhamento de Projetos'), ('Treinamento em Informática e Sistemas de Informação', 'Treinamento em Informática e Sistemas de Informação'), ('Humanização', 'Humanização')], max_length=55),
        ),
    ]
