# Generated by Django 2.0 on 2017-12-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_auto_20171229_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelavaliacao',
            name='solicitacao_n',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.ModelSolicitacao'),
        ),
    ]
