# Generated by Django 2.0 on 2017-12-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_auto_20171229_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsolicitacao',
            name='status',
            field=models.CharField(blank=True, default='Não Avaliada', max_length=20, verbose_name='Status'),
        ),
    ]
