# Generated by Django 2.0 on 2017-12-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0007_modelsolicitacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsolicitacao',
            name='status',
            field=models.CharField(blank=True, default='em avaliação', max_length=20, verbose_name='Status'),
        ),
    ]
